#!/bin/bash

export PATH="/opt/homebrew/bin:$PATH"
export XDG_CONFIG_HOME="~/.config"

STR="+WikiIndex"

while getopts 'j' OPTION; do
    case "$OPTION" in
        j)
            STR="+WikiJournal"
    esac
done

open /Applications/iTerm.app

osascript - "$STR" <<'END'
on run argv -- argv is a list of strings
    tell application "iTerm2"
        # start iterm if it's not already running - is there a way to do this without creating a window?
        activate
        # TODO - only create a new window if called with -karabiner flag
        set activeWindow to (create window with default profile)
        # TODO - otherwise, set activeWindow to the window call was made from
        tell current session of activeWindow
            # here we want to find and connect to the session if it exists
            # if not we create it 
            # then we create a new tmux window, run vim . in it with our relevant wiki flag from above 
        end tell
    end tell
end run
END

exit
