#!/bin/bash

export PATH="/opt/homebrew/bin:$PATH"
export XDG_CONFIG_HOME="~/.config"

STR="+WikiIndex"

while getopts 'j' OPTION; do
    case "$OPTION" in
        j)
            STR="+WikiJournal"
    esac
done

open /Applications/iTerm.app

osascript - "$STR" <<'END'
on run argv -- argv is a list of strings
    tell application "iTerm2"
        activate
        set newWindow to (create window with default profile)
        tell current session of newWindow
            write text "tmux-sessionizer ~/wiki"
            write text "tmux send -t wiki 'vim . " & quoted form of item 1 of argv & "' ENTER"
        end tell
    end tell
end run
END

exit
